_pimcore:
    resource: "@PimcoreCoreBundle/Resources/config/routing.yml"

app:
    resource: "../src/Controller/"
    type: annotation

login:
    path: /login
    controller: App\Controller\LoginController::login
    methods: [GET, POST]

register:
    path: /register
    controller: App\Controller\RegisterController::register
    methods: [GET, POST]

logout:
    path: /logout
    controller: App\Controller\LoginController::logout
    methods: [GET, POST]
